import { Prospect } from "@/types/Prospect";

export const prospects: Prospect[] = [
  {
    id: "bd0a35e8-2166-46af-ae7c-771c6d118d61",
    bankAccountNumber: "123123123",
    bankName: "asdasd",
    dateOfBirth: new Date(),
    city: "San carlos de bariloche",
    country: "Argentina",
    document: "123123123",
    email: "email@email.com",
    fullAddress: "asd asd asd 123",
    googleMapsLocation: "",
    invoices: [],
    lastName: "Alvarez",
    name: "Julian",
    omboardingAttempts: 1,
    phoneNumber: "123123123",
    profilePhotoUrl: "123",
    relevantDetails: "relevant details",
    status: "pending",
    taxId: "123",
  },
  {
    id: "bd0a35e8-2166-46af-ae7c-771c6d118d62",
    bankAccountNumber: "123123123",
    bankName: "asdasd",
    dateOfBirth: new Date(),
    city: "San carlos de bariloche",
    country: "Argentina",
    document: "123123123",
    email: "email@email.com",
    fullAddress: "asd asd asd 123",
    googleMapsLocation: "",
    invoices: [],
    lastName: "Doe",
    name: "John",
    omboardingAttempts: 1,
    phoneNumber: "123123123",
    profilePhotoUrl: "123",
    relevantDetails: "relevant details",
    status: "approved",
    taxId: "123",
  },
  {
    id: "bd0a35e8-2166-46af-ae7c-771c6d118d64",
    bankAccountNumber: "123123123",
    bankName: "asdasd",
    dateOfBirth: new Date(),
    city: "San carlos de bariloche",
    country: "Argentina",
    document: "123123123",
    email: "email@email.com",
    fullAddress: "asd asd asd 123",
    googleMapsLocation: "",
    invoices: [],
    lastName: "Doel",
    name: "Mark",
    omboardingAttempts: 1,
    phoneNumber: "123123123",
    profilePhotoUrl: "123",
    relevantDetails: "relevant details",
    status: "declined",
    taxId: "123",
  },
];
